jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 8090
  error:
#    whitelabel:
#      enabled: false
    path: /error
#In this case, the error path is set to '/error', 
#which means that when an error occurs, the application 
#will redirect the client's request to the '/error' endpoint. 
#The application can then handle the error and return a 
#response to the client. This is useful for handling and 
#returning custom error messages or for providing a custom 
#error page for the client.



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal?createDatabaseIfNotExist=true
    password: 1234
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  web:
#    resources:
#      add-mappings: false
#  mvc:
#    throw-exception-if-no-handler-found: true
  